apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ include "ingestion-api.fullname" . }}" 
  annotations:
    ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - "{{ .Values.hostname }}"
    secretName: ingress-tls
  rules:
  - host: "{{ .Values.hostname }}"
    http:
      paths:
      - backend:
          serviceName: "{{ include "ingestion-api.fullname" . }}"
          servicePort: 80
        path: /