apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: test-scaledobject
  labels:
    aadpodidbinding: cloud-resource-access
    app: test-scaledobject
spec:
  scaleType: job
  pollingInterval: 15
  maxReplicaCount: 4
  cooldownPeriod: 10
  jobTargetRef:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 60
    backoffLimit: 6
    template:
      metadata:
        labels:
          aadpodidbinding: cloud-resource-access
          app: test-scaledobject
      spec:
        restartPolicy: Never
        containers:
        - name: consumer-job
          image: "{{ .Values.global.image.repository }}/messageprocessor:{{ .Values.global.image.tag }}"
          env:
          - name: Cloud
            value: "{{ .Values.global.cloud }}"
          - name: StorageFolder
            value: "{{ .Values.storage_folder }}"
          - name: QueueName
            value: "{{ .Values.storage.queue.name }}"
          {{ if eq .Values.global.cloud "azure" }}
          - name: AzureStorageAccountName
            value: "{{ .Values.azureaccount.name }}"
          {{ end }}
          {{ if eq .Values.global.cloud "gcp" }}
          - name: GoogleProjectID
            value: "{{ .Values.gcp.project_id }}"
          - name: GoogleSubscriptionName
            value: "{{ .Values.gcp.pubsub.subscriptionName }}"
          - name: GOOGLE_APPLICATION_CREDENTIALS_JSON
            valueFrom:
              secretKeyRef:
                name: pubsub-secret
                key: GOOGLE_APPLICATION_CREDENTIALS_JSON
          {{ end }}
  triggers:
  {{ if eq .Values.global.cloud "azure" }}
  - type: azure-queue
    metadata:
      queueName: "{{ .Values.storage.queue.name }}"
      accountName: "{{ .Values.azureaccount.name }}"
      useAAdPodIdentity: "true"
  {{ end }}
  {{ if eq .Values.global.cloud "gcp" }}
  - type: gcp-pubsub
    metadata:
      subscriptionSize: "1"
      subscriptionName: "{{ .Values.gcp.pubsub.subscriptionName }}"
      credentials: GOOGLE_APPLICATION_CREDENTIALS_JSON
  {{ end }}