apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "keda.labels" . | nindent 4 }}
  name: {{ template "keda.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ template "keda.fullname" . }}
      instance: {{ template "keda.fullname" . }}-instance
  template:
    metadata:
      labels:
        name: {{ template "keda.fullname" . }}
        instance: {{ template "keda.fullname" . }}-instance
        aadpodidbinding: cloud-resource-access
    spec:
      serviceAccountName: {{ template "keda.serviceAccountName" . }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.global.image.repository }}/keda:{{ .Values.global.image.tag }}"
        imagePullPolicy: Always
        args:
        - /adapter
        - --secure-port=6443
        - --logtostderr=true
        - --v=2
        - --log-level=debug
        ports:
        - containerPort: 6443
          name: https
        - containerPort: 8080
          name: http
        env:
        - name: queueName
          value: "{{ .Values.storage.queue.name }}"

        {{ if eq .Values.global.cloud "azure" }}
        - name: accountName
          value: "{{ .Values.azureaccount.name }}"
        {{ end }}